services:
  reverse-proxy:
    build:
      context: ./containers/reverse-proxy
      dockerfile: dockerfile
    env_file:
      - ./containers/reverse-proxy/env_file
    environment:
      DYNAMIC_UPSTREAM: true
      RESOLVER: "127.0.0.11 valid=30s"
      STAGE: local
      DOMAINS: >-
        ${BASIC_USER}:${BASIC_PASS}@rdb-browser.${APP_DOMAIN}    -> http://rdb-browser,
        ${BASIC_USER}:${BASIC_PASS}@fake-smtp.${APP_DOMAIN}      -> http://fake-smtp:8025,
        ${BASIC_USER}:${BASIC_PASS}@wordpress1.${APP_DOMAIN}     -> http://wordpress1_web,
        ${BASIC_USER}:${BASIC_PASS}@wordpress2.${APP_DOMAIN}     -> http://wordpress2_web,
        ${BASIC_USER}:${BASIC_PASS}@wordpress3.${APP_DOMAIN}     -> http://wordpress3_web,
        ${BASIC_USER}:${BASIC_PASS}@sub.wordpress3.${APP_DOMAIN} -> http://wordpress3_web,
    volumes:
      - reverse-proxy_data:/var/lib/https-portal
      - reverse-proxy_logs:/var/log/nginx
    networks:
      wordpress-local-network:
        aliases:
          - wordpress-local_reverse-proxy
          - rdb-browser.${APP_DOMAIN}
          - fake-smtp.${APP_DOMAIN}
          - wordpress1.${APP_DOMAIN}
          - wordpress2.${APP_DOMAIN}
          - wordpress3.${APP_DOMAIN}
          - sub.wordpress3.${APP_DOMAIN}
    ports:
      - 80:80
      - 443:443
    extra_hosts:
      - host.docker.internal:host-gateway

  rdb-browser:
    build:
      context: ./containers/rdb-browser
      dockerfile: dockerfile
    env_file:
      - ./containers/rdb-browser/env_file
    environment:
      UPLOAD_LIMIT: 128M
      PMA_HOSTS: >-
        wordpress1_rdb,
        wordpress2_rdb,
        wordpress3_rdb,
    networks:
      wordpress-local-network:
        aliases:
          - wordpress-local_rdb-browser
    extra_hosts:
      - host.docker.internal:host-gateway

  fake-smtp:
    build:
      context: ./containers/fake-smtp
      dockerfile: dockerfile
    env_file:
      - ./containers/fake-smtp/env_file
    environment:
      MP_DATA_FILE: /data/mailpit.db
    volumes:
      - fake-smtp_data:/data
    networks:
      wordpress-local-network:
        aliases:
          - wordpress-local_fake-smtp
    extra_hosts:
      - host.docker.internal:host-gateway

networks:
  wordpress-local-network:
    name: wordpress-local-network
    external: true

volumes:
  reverse-proxy_data:
  reverse-proxy_logs:
  fake-smtp_data:
