FROM php:8.2-apache

WORKDIR /var/www/html

RUN apt-get update && \
    apt-get install -y --no-install-recommends locales vim git curl unzip && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* && \
    locale-gen ja_JP.UTF-8 && \
    localedef -f UTF-8 -i ja_JP ja_JP.UTF-8 && \
    usermod -s /bin/bash www-data && \
    chown www-data:www-data /var/www

COPY ./reverse-proxy.conf /etc/apache2/conf-available/reverse-proxy.conf

RUN a2enmod rewrite && \
    a2enconf reverse-proxy

RUN apt-get update && \
    apt-get install -y --no-install-recommends libcurl4-openssl-dev libmagickwand-dev imagemagick libzip-dev && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* && \
    cp /usr/local/etc/php/php.ini-development /usr/local/etc/php/php.ini && \
    pecl install xdebug-3.3.0 && \
    docker-php-ext-enable xdebug && \
    pecl install imagick-3.7.0 && \
    docker-php-ext-enable imagick && \
    docker-php-ext-install bcmath mysqli exif zip gd intl curl

COPY --from=composer:2.6 /usr/bin/composer /usr/local/bin/composer
COPY --from=wordpress:cli-2.9 /usr/local/bin/wp /usr/local/bin/wp
COPY ./php.ini /usr/local/etc/php/conf.d/php.ini
COPY ./xdebug.ini /usr/local/etc/php/conf.d/xdebug.ini

RUN curl -sL https://raw.githubusercontent.com/axllent/mailpit/develop/install.sh | bash

COPY ./docker-entrypoint-override.sh /usr/local/bin/docker-entrypoint-override.sh

RUN chmod +x /usr/local/bin/docker-entrypoint-override.sh

ENTRYPOINT [ "/usr/local/bin/docker-entrypoint-override.sh" ]

CMD [ "apache2-foreground" ]
